# Configuration file for snakemake pipeline

# Dataset samples
samples: "config/samples.csv"
out_dir: "results/test_data/01_DaPars2"
gtf: "../../../../tests/test_data/gencode_2genes_noChr.vM18.annotation.gtf"
gff3: "../../../../tests/test_data/gencode_2genes_noChr.vM18.annotation.gff3"
# Parameters
# define method specific parameters here
converageThreshold: 10

# Settings
envs: "workflow/envs"
local_log: "logs/local_log"
cluster_log: "logs/cluster_log"
