#------------------------Intronic APA (IPA) counting------------------------
# Calculate the relative expression of intronic APA events across the samples

# load libraries
if ( suppressWarnings(suppressPackageStartupMessages(require("optparse"))) == FALSE ) { stop("[ERROR] Package 'optparse' required! Aborted.") }
if ( suppressWarnings(suppressPackageStartupMessages(require("APAlyzer"))) == FALSE ) { stop("[ERROR] Package 'APAlyzer' required! Aborted.") }
if ( suppressWarnings(suppressPackageStartupMessages(require("GenomicFeatures"))) == FALSE ) { stop("[ERROR] Package 'GenomicFeatures' required! Aborted.") }

#########################
###  PARSE ARGUMENTS  ###
#########################

# Get script name
script = sub("--file=", "", basename(commandArgs(trailingOnly=FALSE)[4]))

# Build description message
description = "Calculate the relative expression of intronic APA (IPA) events\n"
version = "Version: 1.0.0 (Aug 2026)"
requirements = "Requires: optparse, APAlyzer, GenomicFeatures"
msg = paste(description, version, requirements, sep="\n")

# Define list of arguments
option_list = list(
  make_option(
    "--in_preprocessing",
    action = "store",
    type = "character",
    default = FALSE,
    help = "Output of the preprocessing step (provides the list of input bam files)",
    metavar = "files"
  ),
  make_option(
    "--in_pas_reference",
    action = "store",
    type = "character",
    default = FALSE,
    help = "PAS reference regions generated by the pas_reference step",
    metavar = "files"
  ),
  make_option(
    "--strandtype",
    action = "store",
    type = "character",
    default = "NONE",
    help = "strand type of the sample bam files: forward, invert, or NONE [default: %default]",
  ),
  make_option(
    "--nts",
    action = "store",
    type = "integer",
    default = 1,
    help = "number of threads used for counting [default: %default]",
  ),
  make_option(
    "--min_mqs",
    action = "store",
    type = "integer",
    default = 0,
    help = "minimum mapping quality score of the reads to be counted [default: %default]",
  ),
  make_option(
    "--seq_type",
    action = "store",
    type = "character",
    default = "SingleEnd",
    help = "library type of the sample bam files: SingleEnd, or ThreeMostPairEnd
                for paired-end libraries [default: %default]",
  ),
  make_option(
    "--out_counts",
    action = "store",
    type = "character",
    default = FALSE,
    help = "Relative expression of intronic APA events",
    metavar = "files"
  ),
  make_option(
    c("-h", "--help"),
    action = "store_true",
    default = FALSE,
    help = "Show this information and die."
  ),
  make_option(
    c("-v", "--verbose"),
    action = "store_true",
    default = FALSE,
    help = "Print log messages to STDOUT."
  )
)

# Parse command-line arguments
opt_parser = OptionParser(
                usage = paste("Usage:", script, "[OPTIONS] \n", sep = " "),
                option_list = option_list,
                add_help_option = FALSE,
                description = msg)
opt = parse_args(opt_parser)

#------------------------------------------------------------------
# Load variables from the preprocessing and pas_reference steps
load(opt$in_preprocessing)
load(opt$in_pas_reference)

#----------Calculation of relative expression of IPA----------
IPA_OUT = PASEXP_IPA(dfIPA,
                     dfLE,
                     flsall,
                     Strandtype = opt$strandtype,
                     nts = opt$nts,
                     minMQS = opt$min_mqs,
                     SeqType = opt$seq_type)

############################
###  SAVE FINAL OUTPUTS  ###
############################

save(list = c("IPA_OUT"), file = opt$out_counts)
