# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-CSI-UTR-1.1.0
channels:
  - conda-forge
  - bioconda
  - defaults
  - zechxu
dependencies:
  - conda-forge::python=3.8.6
  - conda-forge::markdown=3.3.3
  - conda-forge::pymdown-extensions=8.0.1
  - conda-forge::r-base=4.0.3
#  - conda-forge::perl
  - zechxu::bedtools2=2.25.0
#  - conda-forge::[software]=[version]

  - bioconda::bioconductor-deseq2=1.30.1
  - bioconda::bioconductor-dexseq=1.36.0
  - bioconda::samtools=1.12
