# Configuration file for snakemake pipeline

# Sample table with sample condition, BAM files paths and data type information
# Must be a 3 column CSV file with following headers - 'sample_bam', 'condition', 'data_type'
sample_tbl: "config/samples.csv"

#path to main output directory for run
out_dir: "starting_with_repo_APA_Scan_results/"

gtf: "../../tests/test_data/gencode_2genes_noChr.vM18.annotation.gtf"
genome: "/home/sam/Documents/PhD/Data/Sequence/ensembl_v102_Mus_musculus.GRCm38.dna.primary_assembly.fa"

# Extended mode
#"yes" to run, "no" to not run
run_extended_mode: "no"

# Parameters
# define method specific parameters here
threads: 4
method: "APA-Scan"
paramcode: "AA"

# Settings
envs: "envs"
scripts: "workflow/scripts"
local_log: "logs_starting_with_repo/local_log"
cluster_log: "logs/cluster_log"
