# Configuration file for snakemake pipeline

# Sample table with sample condition, BAM files paths and data type information
# Must be a 3 column CSV file with following headers - 'sample_bam', 'condition', 'data_type'
sample_tbl: "config/samples.csv"

#path to main sample
out_dir: "APA_Scan_results/"

gtf: ""
genome: "mm10.fa"

# Parameters
# define method specific parameters here
threads: 4
method: "APA-Scan"
paramcode: "AA"

# Settings
envs: "envs"
scripts: "workflow/scripts"
local_log: "logs/local_log"
cluster_log: "logs/cluster_log"
