# Configuration file for snakemake pipeline

# Dataset samples
samples: "config/samples.csv"
out_dir: "AA/APA_Scan"
annotation: "mm10.ncbiRefSeq.txt"
genome: "mm10.fa"

# Parameters
# define method specific parameters here
threads: 4
method: "APA-Scan"
paramcode: "AA"

# Settings
envs: "envs"
scripts: "workflow/scripts"
local_log: "logs/local_log"
cluster_log: "logs/cluster_log"
